baseUrl: https://cubly.ru/
languageCode: ru-ru
defaultContentLanguage: ru
theme: terminal
paginate: 5

params:
  # dir name of your blog content (default is `content/posts`)
  contentTypeName: posts
  # ["orange", "blue", "red", "green", "pink"]
  themeColor: red
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems: 3
  # show selector to switch language
  showLanguageSelector: false
  # set theme to full screen width
  fullWidthTheme: false
  # center theme with default width
  centerTheme: false

languages:
  ru:
    languageName: Русский
    title: Your site title
    subtitle: Your site subtitle
    keywords: ''
    menuMore: Show more
    readMore: Read more
    readOtherPosts: Read other posts

    params:
      logo:
        logoText: Terminal
        logoHomeLink: /

    menu:
      main:
      - identifier: about
        name: About
        url: /about
      - identifier: showcase
        name: Showcase
        url: /showcase